// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR Gemini API key',
    appId: '1:578012038991:web:36b3f6e93c89b10c81e73a',
    messagingSenderId: '578012038991',
    projectId: 'sync-bridge-f88c2',
    authDomain: 'sync-bridge-f88c2.firebaseapp.com',
    storageBucket: 'sync-bridge-f88c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR Gemini API key',
    appId: '1:578012038991:android:1309980c9daffb4e81e73a',
    messagingSenderId: '578012038991',
    projectId: 'sync-bridge-f88c2',
    storageBucket: 'sync-bridge-f88c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR Gemini API key',
    appId: '1:578012038991:ios:5ca562ba3f75571881e73a',
    messagingSenderId: '578012038991',
    projectId: 'sync-bridge-f88c2',
    storageBucket: 'sync-bridge-f88c2.firebasestorage.app',
    iosBundleId: 'com.syncbridge.syncBridgeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR Gemini API key',
    appId: '1:578012038991:ios:5ca562ba3f75571881e73a',
    messagingSenderId: '578012038991',
    projectId: 'sync-bridge-f88c2',
    storageBucket: 'sync-bridge-f88c2.firebasestorage.app',
    iosBundleId: 'com.syncbridge.syncBridgeMobile',
  );

}
